import React, { useState, useEffect } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Sparkles, Music, Play, Pause, Volume2, Upload, Camera, Heart, ZoomIn, ZoomOut, ChevronUp, ChevronDown, ChevronLeft, ChevronRight } from 'lucide-react';
import { romanticAudio } from '../utils/audio';
import LoveLetter from './LoveLetter';
import GameCanvas from './GameCanvas';
import ReasonsFlower from './ReasonsFlower';
import TimeCapsuleTimeline from './TimeCapsuleTimeline';

// Import local images generated by Gemini
import lilyIllustration from '../assets/images/lily_illustration_1782469268640.jpg';
import cuteAalu from '../assets/images/cute_aalu_1782469284645.jpg';
import engagementPhoto from '../assets/images/engagement_photo_1782470353595.jpg';

interface MainScreenProps {
  name: string;
  nickname: string;
}

export default function MainScreen({ name, nickname }: MainScreenProps) {
  const [isPlayingMp3, setIsPlayingMp3] = useState(true);
  const [isPlayingSynth, setIsPlayingSynth] = useState(true);
  const [volume, setVolume] = useState(50);
  const [uploadedPhoto, setUploadedPhoto] = useState<string | null>(null);
  const [photoError, setPhotoError] = useState(false);
  const [imgZoom, setImgZoom] = useState(115); // Default 115% zoom
  const [imgX, setImgX] = useState(0); // Offset X in pixels
  const [imgY, setImgY] = useState(15); // Offset Y in pixels (shifted slightly down by default to focus on her face!)
  
  // Backing floating particles state for background
  const [bgParticles, setBgParticles] = useState<Array<{ id: number; x: number; y: number; size: number; duration: number; type: 'petal' | 'heart' }>>([]);

  // Load custom saved photo on mount
  useEffect(() => {
    const saved = localStorage.getItem('karunas_birthday_photo');
    if (saved) {
      setUploadedPhoto(saved);
    }

    // Background particles
    const items = Array.from({ length: 15 }).map((_, i) => ({
      id: i,
      x: Math.random() * 100,
      y: Math.random() * 100,
      size: Math.random() * 12 + 10,
      duration: Math.random() * 12 + 12,
      type: (i % 2 === 0 ? 'petal' : 'heart') as 'petal' | 'heart'
    }));
    setBgParticles(items);
  }, []);

  const handlePhotoUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (file) {
      const reader = new FileReader();
      reader.onloadend = () => {
        const result = reader.result as string;
        setUploadedPhoto(result);
        localStorage.setItem('karunas_birthday_photo', result);
      };
      reader.readAsDataURL(file);
    }
  };

  const toggleMp3 = () => {
    if (isPlayingMp3) {
      romanticAudio.stopMp3();
    } else {
      romanticAudio.startMp3();
    }
    setIsPlayingMp3(!isPlayingMp3);
  };

  const toggleSynth = () => {
    if (isPlayingSynth) {
      romanticAudio.stopMusicBox();
    } else {
      romanticAudio.playMusicBox();
    }
    setIsPlayingSynth(!isPlayingSynth);
  };

  const handleVolumeChange = (e: React.ChangeEvent<HTMLInputElement>) => {
    const val = parseInt(e.target.value);
    setVolume(val);
    romanticAudio.setVolume(val / 100);
  };

  return (
    <div className="relative min-h-screen w-full bg-gradient-to-b from-[#FEF4F4] via-[#FFFDF9] to-[#EBF3E8] py-12 px-4 md:px-8 select-none overflow-x-hidden">
      
      {/* Soft Background floating particles */}
      <div className="absolute inset-0 pointer-events-none overflow-hidden">
        {bgParticles.map((p) => (
          <motion.div
            key={p.id}
            className="absolute"
            style={{
              left: `${p.x}%`,
              top: `${p.y}%`,
              opacity: 0.15,
            }}
            animate={{
              y: ['0vh', '110vh'],
              x: ['-5vw', '5vw'],
              rotate: [0, 360],
            }}
            transition={{
              duration: p.duration,
              repeat: Infinity,
              ease: 'linear',
            }}
          >
            {p.type === 'petal' ? (
              <svg width={p.size} height={p.size} viewBox="0 0 24 24" fill="none">
                <path
                  d="M12 2C12 2 15 8 18 11C21 14 20 18 16 20C12 22 12 18 12 18C12 18 12 22 8 20C4 18 3 14 6 11C9 8 12 2 12 2Z"
                  fill="#F48FB1"
                />
              </svg>
            ) : (
              <Heart size={p.size} className="text-pink-300 fill-pink-200" />
            )}
          </motion.div>
        ))}
      </div>

      {/* FLOATING MUSIC CONTROLLER PANEL */}
      <motion.div
        id="floating-music-controller"
        initial={{ opacity: 0, y: 50 }}
        animate={{ opacity: 1, y: 0 }}
        className="fixed bottom-4 right-4 z-50 bg-white/80 backdrop-blur-md border border-pink-100/50 rounded-full px-4 py-2.5 shadow-[0_10px_30px_rgba(244,143,177,0.2)] flex items-center gap-3.5"
      >
        <div className="flex items-center gap-1.5">
          <Music size={14} className="text-pink-500 animate-spin" style={{ animationDuration: '6s' }} />
          <span className="font-serif text-[11px] font-bold text-gray-600 uppercase tracking-wider">Birthday Tune</span>
        </div>

        <div className="h-4 w-[1px] bg-gray-200" />

        {/* MP3 Controller */}
        <button
          id="toggle-mp3-btn"
          onClick={toggleMp3}
          className="p-1 text-pink-500 hover:text-pink-600 hover:bg-pink-50 rounded-full cursor-pointer transition-colors"
          title={isPlayingMp3 ? "Pause Instrumental MP3" : "Play Instrumental MP3"}
        >
          {isPlayingMp3 ? <Pause size={15} /> : <Play size={15} />}
        </button>

        {/* Synth Controller */}
        <button
          id="toggle-synth-btn"
          onClick={toggleSynth}
          className={`p-1 rounded-full cursor-pointer transition-colors text-xs font-semibold flex items-center justify-center border ${
            isPlayingSynth 
              ? 'bg-pink-100/50 border-pink-200 text-pink-600' 
              : 'bg-gray-50 border-gray-200 text-gray-500 hover:bg-gray-100'
          }`}
          title="Toggle Music Box Chimes Synth"
        >
          <span>Box</span>
        </button>

        <div className="h-4 w-[1px] bg-gray-200 hidden sm:block" />

        {/* Volume slider (hidden on small phones) */}
        <div className="items-center gap-1.5 hidden sm:flex">
          <Volume2 size={13} className="text-gray-400" />
          <input
            id="audio-volume-slider"
            type="range"
            min="0"
            max="100"
            value={volume}
            onChange={handleVolumeChange}
            className="w-16 h-1 bg-pink-100 rounded-lg appearance-none cursor-pointer accent-pink-500"
          />
        </div>
      </motion.div>

      {/* MAIN CONTAINER */}
      <div className="max-w-4xl mx-auto flex flex-col items-center gap-12 relative z-10">
        
        {/* Header Typography with Gold Sparkles */}
        <header className="text-center flex flex-col items-center">
          <motion.div
            initial={{ scale: 0.9, opacity: 0 }}
            animate={{ scale: 1, opacity: 1 }}
            transition={{ duration: 1 }}
            className="flex items-center gap-2 text-pink-500 text-xs font-semibold uppercase tracking-[0.2em] mb-3"
          >
            <Sparkles size={14} className="animate-pulse text-amber-500" />
            <span>Celebrating Karuna Dahal</span>
            <Sparkles size={14} className="animate-pulse text-amber-500" />
          </motion.div>

          <motion.h1
            initial={{ y: -20, opacity: 0 }}
            animate={{ y: 0, opacity: 1 }}
            transition={{ duration: 1.2, delay: 0.1 }}
            className="font-serif text-3xl md:text-5xl text-pink-700/95 font-bold tracking-tight text-glow-pink max-w-2xl leading-tight"
          >
            Happy 19th Birthday, My Beautiful Baby!
          </motion.h1>

          <p className="font-cursive text-3xl text-amber-700/80 mt-2 font-medium">
            May your day bloom brighter than any Lily...
          </p>
        </header>

        {/* TOP HERO PHOTO BANNER */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1.2, delay: 0.2 }}
          className="w-full max-w-2xl bg-white/95 backdrop-blur-md rounded-3xl p-6 md:p-8 shadow-[0_20px_50px_rgba(225,29,72,0.15)] border border-rose-100 flex flex-col items-center relative group hover:shadow-[0_25px_60px_rgba(225,29,72,0.22)] transition-all duration-500"
        >
          {/* Beautiful Digital Frame Wrapper with soft glow and rose/amber accent borders (Cozy Red & Gold) */}
          <div className="relative w-full aspect-[4/3] max-w-lg rounded-3xl p-1.5 bg-gradient-to-tr from-rose-600 via-amber-400 to-rose-500 shadow-[0_15px_35px_rgba(225,29,72,0.25)] flex flex-col items-center justify-center overflow-hidden">
            <div className="w-full h-full rounded-2xl overflow-hidden border border-white/20 bg-rose-50 flex items-center justify-center relative">
              <img
                src="https://i.ibb.co/XBPRJ7c/IMG-20260620-WA0022.jpg"
                alt="My Beautiful Karuna"
                className="w-full h-full object-cover transition-transform duration-300"
                style={{
                  transform: `scale(${imgZoom / 100}) translate(${imgX}px, ${imgY}px)`,
                  transformOrigin: 'center center'
                }}
                referrerPolicy="no-referrer"
              />
              {/* Vignette Overlay */}
              <div className="absolute inset-0 bg-gradient-to-t from-black/60 via-transparent to-transparent pointer-events-none" />
              
              {/* Caption inside the Frame */}
              <div className="absolute bottom-4 inset-x-0 flex flex-col items-center justify-center text-white drop-shadow-[0_2px_6px_rgba(0,0,0,0.9)] z-10 px-3 text-center">
                <div className="flex items-center gap-1.5 bg-black/40 backdrop-blur-sm px-4 py-1.5 rounded-full border border-white/10">
                  <Heart size={14} className="text-rose-500 fill-rose-500 animate-pulse" />
                  <span className="font-serif font-bold text-xs md:text-sm tracking-wide">Karuna (My Aalu) ❤️</span>
                </div>
              </div>
            </div>
          </div>

          {/* Elegant Image Adjuster Toolbar */}
          <div className="mt-6 flex flex-wrap items-center justify-center gap-3 bg-rose-50/75 border border-rose-100/60 backdrop-blur-sm px-4 py-2 rounded-full shadow-sm z-10">
            <span className="text-[10px] font-mono text-rose-700/80 uppercase font-bold tracking-wider mr-1">Position Portrait:</span>
            
            {/* Zoom Controls */}
            <div className="flex items-center gap-1 bg-white/90 p-0.5 rounded-full shadow-sm border border-rose-100">
              <button 
                onClick={() => setImgZoom(prev => Math.max(80, prev - 5))}
                className="p-1 hover:bg-rose-100 rounded-full text-rose-600 transition-colors cursor-pointer"
                title="Zoom Out"
              >
                <ZoomOut size={12} />
              </button>
              <span className="text-[10px] font-mono font-bold text-rose-700 w-8 text-center">{imgZoom}%</span>
              <button 
                onClick={() => setImgZoom(prev => Math.min(250, prev + 5))}
                className="p-1 hover:bg-rose-100 rounded-full text-rose-600 transition-colors cursor-pointer"
                title="Zoom In"
              >
                <ZoomIn size={12} />
              </button>
            </div>

            {/* Position Pad Controls */}
            <div className="flex items-center gap-1 bg-white/90 p-0.5 rounded-full shadow-sm border border-rose-100">
              <button 
                onClick={() => setImgY(prev => prev - 5)}
                className="p-1 hover:bg-rose-100 rounded-full text-rose-600 transition-colors cursor-pointer"
                title="Move Up"
              >
                <ChevronUp size={12} />
              </button>
              <button 
                onClick={() => setImgY(prev => prev + 5)}
                className="p-1 hover:bg-rose-100 rounded-full text-rose-600 transition-colors cursor-pointer"
                title="Move Down"
              >
                <ChevronDown size={12} />
              </button>
              <button 
                onClick={() => setImgX(prev => prev - 5)}
                className="p-1 hover:bg-rose-100 rounded-full text-rose-600 transition-colors cursor-pointer"
                title="Move Left"
              >
                <ChevronLeft size={12} />
              </button>
              <button 
                onClick={() => setImgX(prev => prev + 5)}
                className="p-1 hover:bg-rose-100 rounded-full text-rose-600 transition-colors cursor-pointer"
                title="Move Right"
              >
                <ChevronRight size={12} />
              </button>
            </div>

            {/* Reset Button */}
            <button
              onClick={() => {
                setImgZoom(115);
                setImgX(0);
                setImgY(15);
              }}
              className="px-2.5 py-0.5 bg-white hover:bg-rose-50 text-[10px] font-bold text-rose-600 border border-rose-200 rounded-full shadow-sm transition-colors cursor-pointer"
            >
              Reset
            </button>
          </div>
        </motion.div>

        {/* REVEAL CARDS ROW */}
        <div className="w-full grid grid-cols-1 md:grid-cols-12 gap-8 items-start">
          
          {/* LEFT SIDE: Lily Picture Frame & Mascot Blurb */}
          <div className="md:col-span-5 flex flex-col gap-8 items-center w-full">
            
            {/* Glowing Engagement Polaroid Frame Card */}
            <motion.div
              initial={{ opacity: 0, x: -30 }}
              animate={{ opacity: 1, x: 0 }}
              transition={{ duration: 1 }}
              className="bg-white/95 backdrop-blur-md rounded-3xl p-6 shadow-[0_20px_50px_rgba(225,29,72,0.12)] border border-rose-100 flex flex-col items-center w-full relative group hover:shadow-[0_25px_55px_rgba(225,29,72,0.18)] transition-all duration-500"
            >
              {/* Cute Heart Pushpin Pin Decoration at the top */}
              <div className="absolute -top-3 left-1/2 -translate-x-1/2 z-20 flex flex-col items-center pointer-events-none">
                <div className="w-5 h-5 rounded-full bg-rose-600 shadow-md relative flex items-center justify-center">
                  <div className="w-2 h-2 rounded-full bg-white/40 absolute top-0.5 left-0.5" />
                  <Heart size={10} className="text-white fill-white" />
                </div>
                <div className="w-0.5 h-4 bg-gray-400/80 -mt-0.5 shadow-sm" />
              </div>

              {/* Beautiful Digital Frame Wrapper with soft glow and lily accent borders (Cozy Red & Gold) */}
              <label 
                htmlFor="main-photo-uploader"
                className="relative w-full aspect-[4/3] rounded-2xl cursor-pointer group-hover:scale-[1.03] transition-all duration-500 p-1.5 bg-gradient-to-tr from-rose-600 via-amber-400 to-pink-300 shadow-[0_15px_35px_rgba(225,29,72,0.25)] flex flex-col items-center justify-center overflow-hidden"
              >
                <div className="w-full h-full rounded-xl overflow-hidden border border-white/20 bg-[#FFFDFB] flex items-center justify-center relative">
                  {uploadedPhoto ? (
                    <img
                      src={uploadedPhoto}
                      alt="Baby and Me"
                      className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
                      referrerPolicy="no-referrer"
                    />
                  ) : (
                    <div className="relative w-full h-full">
                      <img
                        src={photoError ? engagementPhoto : "https://i.ibb.co/9HfMtS4g/IMG-20260306-WA0007.jpg"}
                        alt="Baby and Me"
                        onError={() => setPhotoError(true)}
                        className="w-full h-full object-cover transition-transform duration-700 group-hover:scale-105"
                        referrerPolicy="no-referrer"
                      />
                      <div className="absolute bottom-3 right-3 bg-rose-600/85 backdrop-blur-sm hover:bg-rose-700 text-white p-2 rounded-full transition-colors shadow-lg z-10">
                        <Camera size={14} />
                      </div>
                    </div>
                  )}
                </div>
              </label>

              {/* Polaroid Handwritten Caption */}
              <div className="mt-4 text-center select-none">
                <p className="font-cursive text-2xl text-rose-700/90 font-semibold tracking-wide">
                  Us, Together Forever 💍❤️
                </p>
                <span className="font-mono text-[9px] text-amber-600/90 font-bold tracking-widest uppercase block mt-1">
                  Engaged • Tap Photo To Upload Your Own
                </span>
              </div>

              {/* Hidden File input */}
              <input
                id="main-photo-uploader"
                type="file"
                accept="image/*"
                onChange={handlePhotoUpload}
                className="hidden"
              />

              {/* Decorative Lily Garland Illustration Frame Bottom */}
              <div className="absolute -bottom-3 -right-3 w-16 h-16 pointer-events-none opacity-90 hover:scale-110 transition-transform duration-300">
                <img src={lilyIllustration} className="w-full h-full object-contain rounded-full border-2 border-white shadow-md" referrerPolicy="no-referrer" />
              </div>
            </motion.div>

            {/* CUTIE MASCOT BOARD: The Sweet "Aalu" Potato */}
            <motion.div
              initial={{ opacity: 0, y: 30 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 1, delay: 0.2 }}
              className="bg-white/60 backdrop-blur-md rounded-3xl p-5 border border-amber-100 shadow-[0_12px_25px_rgba(141,110,99,0.06)] flex items-center gap-4 w-full relative"
            >
              {/* Potato Blushing Face */}
              <div className="w-16 h-16 rounded-2xl overflow-hidden border border-amber-200 shrink-0 shadow-sm">
                <img
                  src={cuteAalu}
                  alt="Cute Aalu"
                  className="w-full h-full object-cover"
                  referrerPolicy="no-referrer"
                />
              </div>

              {/* Speech Bubble */}
              <div className="relative flex-grow bg-amber-50/50 border border-amber-100/80 rounded-2xl p-3 text-xs leading-relaxed text-amber-900/90">
                <div className="absolute -left-2.5 top-6 w-0 h-0 border-y-6 border-y-transparent border-r-8 border-r-amber-50" />
                <strong className="text-pink-600 block mb-0.5">Your Cute Aalu says:</strong>
                "Pst, Baby! Happy 19th Birthday! 🎂 Make sure to play my catch game below and grab your special love notes! Love you loads! 🥔💕"
              </div>
            </motion.div>

          </div>

          {/* RIGHT SIDE: Love Letter Card */}
          <div className="md:col-span-7 flex flex-col gap-6 w-full">
            <LoveLetter name={name} nickname={nickname} />
          </div>

        </div>

        {/* RELATIONSHIP TIMELINE SECTION */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.8 }}
          className="w-full mt-6"
        >
          <TimeCapsuleTimeline />
        </motion.div>

        {/* 19 REASONS FLOWER SECTION */}
        <motion.div
          initial={{ opacity: 0, y: 40 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true, margin: "-100px" }}
          transition={{ duration: 0.8 }}
          className="w-full mt-6"
        >
          <ReasonsFlower />
        </motion.div>

        {/* INTERACTIVE MINI-GAME SECTION */}
        <div className="w-full grid grid-cols-1 md:grid-cols-12 gap-8 items-center mt-4">
          <div className="md:col-span-6 w-full">
            <motion.div
              initial={{ opacity: 0, x: -30 }}
              whileInView={{ opacity: 1, x: 0 }}
              viewport={{ once: true }}
              className="flex flex-col gap-4 text-center md:text-left pr-4"
            >
              <span className="text-xs font-semibold text-emerald-600 uppercase tracking-widest">Our Little Play Room</span>
              <h2 className="font-serif text-2xl md:text-3xl text-pink-700/90 font-bold leading-tight">
                Play "Our Romantic Memory Catch"! 🥔🌸
              </h2>
              <p className="font-sans text-sm text-gray-500 leading-relaxed">
                I designed this simple, super cute game just for you! Items are falling from the top: fresh <strong>Lilies</strong>, glowing <strong>Hearts</strong>, and adorable round <strong>Potatoes ("Aalu")</strong>!
              </p>
              <p className="font-sans text-sm text-gray-500 leading-relaxed">
                Move the flower basket left and right to catch them! Every caught item increases your Love Meter and unlocks custom love notes on screen. See if you can score at least <strong>19 points</strong> to read my special 19th birthday message!
              </p>
            </motion.div>
          </div>

          <div className="md:col-span-6 w-full">
            <GameCanvas nickname={nickname} />
          </div>
        </div>

        {/* Footer Greetings */}
        <footer className="text-center mt-6 flex flex-col items-center">
          <Heart size={20} className="text-rose-400 fill-rose-200 animate-heartbeat mb-2" />
          <p className="font-cursive text-3xl text-amber-900/70">
            Loving you forever, Baby
          </p>
          <p className="font-mono text-[9px] text-gray-400 mt-2 uppercase tracking-widest">
            June 27th • Karuna's 19th Birthday Card • Crafted with Infinite Love
          </p>
        </footer>

      </div>
    </div>
  );
}
